version: "3.6"

services:
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_LOG_MIN_LEVEL: "fatal"
    command: ["postgres", "-c", "log_min_messages=fatal"]
    restart: unless-stopped
  backup:
    image: prodrigestivill/postgres-backup-local:13-alpine
    restart: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ${DOCKER_DB_BACKUP_PATH}:/backups/:z
    links:
      - db
    depends_on:
      - db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_EXTRA_OPTS=${POSTGRES_EXTRA_OPTS}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - SCHEDULE=${SCHEDULE}
  bot:
    build:
      context: .
      dockerfile: Dockerfile
      args: ["TZ=Europe/Prague"]

    env_file: .env

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./:/pumpkin-py/:z
    command: python pumpkin.py
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data:
