version: "3.6"

services:
  db:
    image: docker.io/postgres:13-alpine
    container_name: pumpkin-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_LOG_MIN_LEVEL: "fatal"
    command: ["postgres", "-c", "log_min_messages=fatal"]
    restart: unless-stopped
  backup:
    image: docker.io/prodrigestivill/postgres-backup-local:13-alpine
    container_name: pumpkin-backup
    restart: unless-stopped
    volumes:
      - ${DOCKER_DB_BACKUP_PATH}:/backups/:z
    links:
      - pumpkin-db
    depends_on:
      - pumpkin-db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_EXTRA_OPTS=${POSTGRES_EXTRA_OPTS}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - SCHEDULE=${SCHEDULE}
  bot:
    image: docker.io/czechbol/pumpkin-py
    container_name: pumpkin-bot
    env_file: .env
    volumes:
      - ./:/pumpkin-py/:z
    depends_on:
      - pumpkin-db
    restart: unless-stopped

volumes:
  postgres_data:
